DROP TABLE IF EXISTS word_card;
DROP TABLE IF EXISTS result;
DROP TABLE IF EXISTS wuser;

CREATE TABLE wuser (
  id   INT  NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  PRIMARY KEY (id)
)
  ENGINE = INNODB;

CREATE TABLE word_card (
  id       INT  NOT NULL AUTO_INCREMENT,
  pic_location VARCHAR(255),
  theme VARCHAR(255),
  hun VARCHAR(100),
  eng VARCHAR(100),
  PRIMARY KEY (id)
)
  ENGINE = INNODB;

CREATE TABLE result (
  id       INT  NOT NULL AUTO_INCREMENT,
  result   INT,
  PRIMARY KEY (id)
)
  ENGINE = INNODB;

